In [2]:
# Importing required libraries
import pandas as pd
import numpy as np
import matplotlib as plt

In [3]:
# Loading dataset 
df = pd.read_csv("retail_sales.csv",
                 parse_dates=['Date'])

In [4]:
# Understanding data to drive features
print("Dataset shape(rows, columns) is", df.shape)
print("\nDataset column types are \n", df.dtypes)

Dataset shape(rows, columns) is (1825, 6)

Dataset column types are
 Date        datetime64[us]
Category               str
Sales              float64
Quantity           float64
Profit             float64
Region                 str
dtype: object

In [5]:
# Displaying data head
print(df.head())

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [6]:
# Converting "Category" and "Region" columns to categories for better manipulation
df['Category'] = df['Category'].astype('category')
df['Region'] = df['Region'].astype('category')

print(df.dtypes)
print("\nConverted to categories successfully")

Date        datetime64[us]
Category          category
Sales              float64
Quantity           float64
Profit             float64
Region            category
dtype: object

Converted to categories successfully

In [7]:
# Checking for missing values 
df.isna().sum()

Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64

In [8]:
# Handling missing values
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])
df['Sales'] = df['Sales'].fillna(df['Sales'].median())
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Region'] = df['Region'].fillna(df['Region'].mode()[0])

df.isna().sum()

Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
dtype: int64

In [9]:
# Summary Statistics
df.describe()

                      Date        Sales     Quantity       Profit
count                 1825  1825.000000  1825.000000  1825.000000
mean   2023-07-02 00:00:00   980.501573    10.053699   248.696130
min    2023-01-01 00:00:00     0.000000     0.000000     0.000000
25%    2023-04-02 00:00:00   784.267165     5.000000   156.916498
50%    2023-07-02 00:00:00   997.725134    10.000000   229.344557
75%    2023-10-01 00:00:00  1208.163533    15.000000   324.867847
max    2023-12-31 00:00:00  1888.932537    19.000000   703.228418
std                    NaN   336.572425     5.507806   118.159627

In [10]:
# Checking Profit against Category
print("Skewness of Profit column: ", df['Profit'].skew())
df.groupby('Category')['Profit'].describe()

Skewness of Profit column:  0.6702121466996879

,count,mean,std,min,25%,50%,75%,max
Category,,,,,,,,
Books,364.0,253.583660,117.922429,22.157708,166.394659,235.483626,324.232402,652.843041
Clothing,369.0,246.312838,118.959387,8.140877,149.253555,225.271072,334.726110,649.168113
Electronics,361.0,250.525479,120.134380,0.000000,157.754976,226.479496,317.128339,703.228418
Home Goods,364.0,240.241264,111.652827,0.000000,156.745914,219.101295,305.646907,608.800018
NaN?,1.0,88.591355,NaN,88.591355,88.591355,88.591355,88.591355,88.591355
Nan,1.0,253.433301,NaN,253.433301,253.433301,253.433301,253.433301,253.433301
Null,1.0,381.784578,NaN,381.784578,381.784578,381.784578,381.784578,381.784578
Sports,364.0,252.926431,121.988465,21.368432,155.847708,237.692829,328.592851,624.033248

In [11]:
# Dropping rows with values NaN?, Nan, Null
df = df.replace(['NaN?', 'Nan', 'Null', ' '], np.nan)
df.dropna()

           Date     Category        Sales  Quantity      Profit Region
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
5    2023-01-02  Electronics   722.775149      10.0   82.396149   West
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

[1821 rows x 6 columns]

In [12]:
df.groupby('Category')['Profit'].describe()

,count,mean,std,min,25%,50%,75%,max
Category,,,,,,,,
Books,364.0,253.583660,117.922429,22.157708,166.394659,235.483626,324.232402,652.843041
Clothing,369.0,246.312838,118.959387,8.140877,149.253555,225.271072,334.726110,649.168113
Electronics,361.0,250.525479,120.134380,0.000000,157.754976,226.479496,317.128339,703.228418
Home Goods,364.0,240.241264,111.652827,0.000000,156.745914,219.101295,305.646907,608.800018
Sports,364.0,252.926431,121.988465,21.368432,155.847708,237.692829,328.592851,624.033248

In [17]:
# Printing rows with 0 sales but non-zero 'Quantity' and 'Profit' column
print("Rows with 0 sales and non-zero Profit values")
print(df.loc[(df['Sales']<=0) & (df['Profit'] != 0) & (df['Quantity'] != 0)])
print("\nTotal rows: ")
print(((df['Sales']<=0) & (df['Profit'] != 0) & (df['Quantity'] != 0)).sum())

Rows with 0 sales and non-zero Profit values
          Date     Category  Sales  Quantity      Profit Region
13  2023-01-03       Sports    0.0      10.0  371.526571  South
59  2023-01-12        Books    0.0       1.0  362.747466   East
102 2023-01-21   Home Goods    0.0       4.0  190.598776  North
129 2023-01-26        Books    0.0       8.0  168.887278  South
133 2023-01-27       Sports    0.0       6.0  497.017998   West
138 2023-01-28       Sports    0.0       5.0  439.982225  South
181 2023-02-06     Clothing    0.0       8.0  258.536790   West
187 2023-02-07   Home Goods    0.0      17.0  181.107404  North
226 2023-02-15     Clothing    0.0      11.0  273.405002   East
230 2023-02-16  Electronics    0.0      11.0  269.610201   West
234 2023-02-16        Books    0.0      17.0  117.559037  South
277 2023-02-25   Home Goods    0.0       7.0  414.445420  South
281 2023-02-26     Clothing    0.0      10.0  286.286667  South
283 2023-02-26       Sports    0.0      11.0  232.319471   East
286 2023-02-27     Clothing    0.0       2.0  139.842676  South
352 2023-03-12   Home Goods    0.0       1.0  453.971937  South
356 2023-03-13     Clothing    0.0       9.0  472.363546   West
363 2023-03-14       Sports    0.0      14.0  171.880443   West
367 2023-03-15   Home Goods    0.0      15.0  207.319605   West
401 2023-03-22     Clothing    0.0       5.0  327.929378  South
407 2023-03-23   Home Goods    0.0       1.0  193.475091   East
410 2023-03-24  Electronics    0.0      14.0  183.929458  South
415 2023-03-25  Electronics    0.0       4.0  412.414536  South
449 2023-03-31        Books    0.0      12.0  156.666207  South
453 2023-04-01       Sports    0.0      18.0  260.622691  North
458 2023-04-02       Sports    0.0      15.0  259.204842  South
462 2023-04-03   Home Goods    0.0       3.0  185.588131  North
476 2023-04-06     Clothing    0.0       3.0  318.511620   West
481 2023-04-07     Clothing    0.0       4.0  421.857000   West
484 2023-04-07        Books    0.0       1.0  273.884688   West
490 2023-04-09  Electronics    0.0       3.0   92.274782  North
520 2023-04-15  Electronics    0.0       4.0  289.304050   West
525 2023-04-16  Electronics    0.0       4.0  153.210888   West
528 2023-04-16       Sports    0.0      19.0  270.577388   West
533 2023-04-17       Sports    0.0      11.0  378.225841  South
547 2023-04-20   Home Goods    0.0      11.0  144.245125  South
550 2023-04-21  Electronics    0.0      15.0  403.068942  North
555 2023-04-22  Electronics    0.0       1.0  139.643277   West
559 2023-04-22        Books    0.0       6.0  315.088936  South
602 2023-05-01   Home Goods    0.0      13.0  451.937088   East
605 2023-05-02  Electronics    0.0       4.0  149.543580  South
610 2023-05-03  Electronics    0.0      12.0  335.387391   West
613 2023-05-03       Sports    0.0       9.0  460.825187   West

Total rows:
43

In [14]:
# Handling these weird rows

In [20]:
print("\nRows with 0 sales and non-zero Quantity values")
print( df.loc[(df['Sales']<=0) & (df['Quantity'] > 0)])

print("\nTotal rows: ")
print(((df['Sales']<=0) & (df['Quantity'] > 0)).sum())

Rows with 0 sales and non-zero Quantity values
          Date     Category  Sales  Quantity      Profit Region
13  2023-01-03       Sports    0.0      10.0  371.526571  South
59  2023-01-12        Books    0.0       1.0  362.747466   East
102 2023-01-21   Home Goods    0.0       4.0  190.598776  North
129 2023-01-26        Books    0.0       8.0  168.887278  South
133 2023-01-27       Sports    0.0       6.0  497.017998   West
138 2023-01-28       Sports    0.0       5.0  439.982225  South
181 2023-02-06     Clothing    0.0       8.0  258.536790   West
187 2023-02-07   Home Goods    0.0      17.0  181.107404  North
226 2023-02-15     Clothing    0.0      11.0  273.405002   East
230 2023-02-16  Electronics    0.0      11.0  269.610201   West
234 2023-02-16        Books    0.0      17.0  117.559037  South
277 2023-02-25   Home Goods    0.0       7.0  414.445420  South
281 2023-02-26     Clothing    0.0      10.0  286.286667  South
283 2023-02-26       Sports    0.0      11.0  232.319471   East
286 2023-02-27     Clothing    0.0       2.0  139.842676  South
312 2023-03-04   Home Goods    0.0      19.0    0.000000   West
352 2023-03-12   Home Goods    0.0       1.0  453.971937  South
356 2023-03-13     Clothing    0.0       9.0  472.363546   West
363 2023-03-14       Sports    0.0      14.0  171.880443   West
367 2023-03-15   Home Goods    0.0      15.0  207.319605   West
401 2023-03-22     Clothing    0.0       5.0  327.929378  South
407 2023-03-23   Home Goods    0.0       1.0  193.475091   East
410 2023-03-24  Electronics    0.0      14.0  183.929458  South
415 2023-03-25  Electronics    0.0       4.0  412.414536  South
449 2023-03-31        Books    0.0      12.0  156.666207  South
453 2023-04-01       Sports    0.0      18.0  260.622691  North
458 2023-04-02       Sports    0.0      15.0  259.204842  South
462 2023-04-03   Home Goods    0.0       3.0  185.588131  North
465 2023-04-04  Electronics    0.0      12.0    0.000000   West
476 2023-04-06     Clothing    0.0       3.0  318.511620   West
481 2023-04-07     Clothing    0.0       4.0  421.857000   West
484 2023-04-07        Books    0.0       1.0  273.884688   West
490 2023-04-09  Electronics    0.0       3.0   92.274782  North
520 2023-04-15  Electronics    0.0       4.0  289.304050   West
525 2023-04-16  Electronics    0.0       4.0  153.210888   West
528 2023-04-16       Sports    0.0      19.0  270.577388   West
533 2023-04-17       Sports    0.0      11.0  378.225841  South
547 2023-04-20   Home Goods    0.0      11.0  144.245125  South
550 2023-04-21  Electronics    0.0      15.0  403.068942  North
555 2023-04-22  Electronics    0.0       1.0  139.643277   West
559 2023-04-22        Books    0.0       6.0  315.088936  South
602 2023-05-01   Home Goods    0.0      13.0  451.937088   East
605 2023-05-02  Electronics    0.0       4.0  149.543580  South
610 2023-05-03  Electronics    0.0      12.0  335.387391   West
613 2023-05-03       Sports    0.0       9.0  460.825187   West

Total rows:
45